### PR TITLE
Plotting funs

### PR DESCRIPTION
**Pull request by emdann**
I have made a function to visualize the logFC of neighbourhoods on the UMAP of the whole dataset. I still find this the most interpretable visualisation of the test results. 

I've been playing with other options re-embedding neighbourhoods but they don't look as good and I wonder if we really need to do this (to discuss soon).

### CODE REVIEW

**Comment by emdann** [comment]
I have added the `projectNeighbourhoodExpression` function. This implementation uses the PC loadings matrix (genes X pcs) for the projection, and I want this to be stored as `attr(reducedDim(x, "PCA"), "rotation")`.  If we keep it as is I suggest we modify the function `buildGraph` to store this info [here](https://github.com/MikeDMorgan/miloR/blob/f58e0123d8acba812ce0bb8039458cfea1cfd5ce/R/buildGraph.R#L63-L73). 

It's a matter of adding
```
attributes(reducedDim(x, "PCA"))[["rotation"]] <- x_pca$rotation
```
@MikeDMorgan if you think this is sensible I will modify `buildGraph.R` accordingly and add to the PR

**Comment by MikeDMorgan** [comment]
The issue with storing this in the `reducedDim(x, "rotation")` slot is that the dimensionality doesn't match to the underlying structure of the SingleCellExperiment object. It might be better served being stored in the rowData(x) slot as then the matrix dimensions will conform as expected.

**Comment by emdann** [comment]
Wait, but it's not an element in `reducedDim`, but an attribute of `reducedDim(x, "PCA")`. For example `scater::runPCA` stores the loadings in the same way.

**Comment by MikeDMorgan** [comment]
Hmm, OK. I hadn't realised you could add attributes to S3 classes in this way. In that case we will need getter and setter methods to access this cleanly, check if it is empty, etc.

**Comment by emdann** [comment]
I might have been overly optimistic about the whole 'projecting nhoods on single-cells' thing. I have tried a few things and none seem to give exactly the nice vix I was hoping for:

1. **PCA projection + UMAP embedding**
```r
nhoods_mat <- projectNeighbourhoodExpression(sim_milo)
full_umap <- uwot::umap(nhoods_mat[,1:30], n_neighbors = 20, metric = "cosine", ret_model=TRUE)
```
Result:


2. **PCA projection + L2 normalization + UMAP embedding** a number of methods that use projection use this normalization
```r
nhoods_mat <- projectNeighbourhoodExpression(sim_milo)
nhoods_mat <- apply(nhoods_mat, 1, function(x) x/.l2norm(x)) %>% t()
full_umap <- uwot::umap(nhoods_mat[,1:30], n_neighbors = 20, metric = "cosine", ret_model=TRUE)
```
Result:


3. **PCA projection + UMAP embedding of single cells + UMAP transform the nhoods** so not recalculating the UMAP coordinates but projecting on the embedding from the single cells
```r
nhoods_mat <- projectNeighbourhoodExpression(sim_milo)
## Run UMAP keeping the model
sc_umap <- uwot::umap(nhoods_mat[str_detect(rownames(nhoods_mat), "nh",negate = TRUE),1:30], n_neighbors = 20, metric = "cosine", ret_model=TRUE)
## Project new data
new_umap <- uwot::umap_transform(nhoods_mat[str_subset(rownames(nhoods_mat), "nh"),][,1:30], sc_umap, init_weighted = TRUE) 
full_umap <- rbind(new_umap, sc_umap$embedding)
```
Results:
00000a

4. **PCA projection + L2 normalization + UMAP embedding of single cells + UMAP transform the nhoods** 
```r
nhoods_mat <- projectNeighbourhoodExpression(sim_milo)
nhoods_mat <- apply(nhoods_mat, 1, function(x) x/.l2norm(x)) %>% t()
## Run UMAP keeping the model
sc_umap <- uwot::umap(nhoods_mat[str_detect(rownames(nhoods_mat), "nh",negate = TRUE),1:30], n_neighbors = 20, metric = "cosine", ret_model=TRUE)
## Project new data
new_umap <- uwot::umap_transform(nhoods_mat[str_subset(rownames(nhoods_mat), "nh"),][,1:30], sc_umap, init_weighted = TRUE) 
full_umap <- rbind(new_umap, sc_umap$embedding)
```
Results:
00000b (2)

5. **PCA projection + UMAP embedding of nhoods only**
```r
nhoods_mat <- projectNeighbourhoodExpression(sim_milo)
nh_umap <- uwot::umap(nhoods_mat[str_detect(rownames(nhoods_mat), "nh"),1:30], n_neighbors = 20, metric = "cosine", ret_model=TRUE)
```
Results:
00000d (2)


I'm running out of ideas here...

**Comment by MikeDMorgan** [comment]
This is the same issue I've seen w.r.t. projecting bulk into single-cell data and _vice versa_ - the variance is so fundamentally different that methods that rely on finding the greatest variance basically fail. 

In the original PCA did you center and scale the data first? I'd also try the L2 or cosine normalisation on _both_ data sets prior to PCA and UMAP - this has yielded marginally better results in the past for combining across datasets...otherwise we might have to revert to just using the neighbourhood index cells :(

**Comment by MikeDMorgan** [comment]
On a slightly separate note - what happens if you do a separate PCA on the nhoods - then use reducedMNN from `batchelor`, or alternatively use CCA but define the MNN anchors as the neighbourhood indices and their matching nhood average expression? Does that make sense?

**Comment by emdann** [comment]
Thanks for the suggestions Mike, looks like it really was a matter of scaling! :tada: :tada: :tada:

**Comment by MikeDMorgan** [comment]
Awesome, nice!

**Comment by MikeDMorgan** [comment]
If we have this, can we construct an abstracted graph then, where the edges between neighbourhoods is some sort of aggregation of edges of the cells in each neighbourhoods? I'm not sure what kind of graph we'd call that though...

**Comment by emdann** [comment]
Do you mean an abstracted graph on the UMAP embedding?

**Comment by MikeDMorgan** [comment]
For now I think this joint UMAP works very nicely, but I was thinking of additional visualisations. I'm just speculating here, so please shoot it down if it's incredibly stupid.

I was thinking of something simpler, where we have <i>nhood<sub>i</sub></i> and <i>nhood<sub>j</sub></i>, can we draw an edge between them that is proportional to the sum of edges between the cells in the 2 neighbourhoods (similar idea to the PAGA concept), but dropping/ignoring/weighting cells that appear in both neighbourhoods?

I guess this could use the kNN that underpins the UMAP - but that seems redundant as we have the graph already. I guess the issue is keeping the same force-directed layout though...

**Pull request merged**
