### PR TITLE
First vignette

### PR DESCRIPTION
**Pull request by emdann**
I've made a super basic demo for usage of the package

### CODE REVIEW

**Comment by MikeDMorgan** [comment]
Hi @emdann Could you pull in the latest master branch - that should (hopefully) fix the failing Travis build.

**Comment by emdann** [comment]
Not sure what's happening here, the only warning I get now from R CMD check is the following:
```r
> checking files in ‘vignettes’ ... WARNING
  Files in the 'vignettes' directory but no files in 'inst/doc':
    ‘milo_demo.Rmd’, ‘milo_demo.html’
  Package has no Sweave vignette sources and no VignetteBuilder field.
```

**Comment by MikeDMorgan** [comment]
I think you need to add some packages to the DESCRIPTION - see here:
https://www.bioconductor.org/packages/release/bioc/vignettes/BiocStyle/inst/doc/AuthoringRmdVignettes.html

**Comment by MikeDMorgan** [comment]
The object `x.traj` doesn't exist - I had to change this to `sim_trajectory` to fix build and check errors.

**Comment by emdann** [comment]
This is not quite ready yet, the vignette still breaks the check. I'm trying to figure this out.

**Comment by MikeDMorgan** [comment]
> This is not quite ready yet, the vignette still breaks the check. I'm trying to figure this out.

No worries - it looks like some packages are missing:

```Error: processing vignette 'milo_demo.Rmd' failed with diagnostics:

there is no package called 'uwot'

--- failed re-building ‘milo_demo.Rmd’

SUMMARY: processing the following file failed:

  ‘milo_demo.Rmd’

Error: Vignette re-building failed.

Execution halted

**Comment by emdann** [comment]
I'm a bit confused because I am not using `uwot` just `runUMAP` from `scater`, which is in the `DESCRIPTION`.

**Comment by emdann** [comment]
For now, I've removed (commented) the chunk that demonstrates how to use `buildFromAdjacency`, because this will need to be changed anyway and it was breaking the vignette

**Comment by MikeDMorgan** [comment]
Great - I'll merge then.

**Pull request merged**
