### PR TITLE
Nhood graph visualization function

### PR DESCRIPTION
**Pull request by emdann**
Added `nhoodGraph` slot to `Milo` object, which can be used to visualize the neighbourhoods using `plotNhoodGraph` or `plotNhoodGraphDA` to visualize DA test results

### CODE REVIEW

**Comment by emdann** [comment]
I had a case of severe git madness while trying to send this PR, pls check I am not breaking anything

**Comment by MikeDMorgan** [comment]
Currently the `plotNhoods.R` file is missing from the DESCRIPTION file, hence the build and checks will fail. You can see where the other files have been added.  Moreover, I don't think you were working on the up-to-date master branch, as many of the documentation changes, etc in unrelated files have also been changed/removed.  Could you reconcile these to make sure that they are still correct?

**Comment by MikeDMorgan** [comment]
I'd advise saving the specific changes outside of the miloR directory, use git rebase to revert to the your last commit _before_ you first added changes, then pull in the master branch and merge. After that, then add in your changes - that might be the easiest thing to do.

For reference, _always_ make sure you have the most up-to-date commits before making any changes, or else be prepared to descend in to a git merge conflict hell!

**Comment by emdann** [comment]
Holy moly, sorry for this mess. That's what you get for trying to finish things up at the end of the week.

**Comment by MikeDMorgan** [comment]
No worries - there's a reason it's called `git`:
https://www.google.com/search?client=firefox-b-e&q=git+dictionary

**Comment by emdann** [comment]
I've tried to revert to latest master + one new commit with all my changes, but git doesn't let me push without pulling, because remote branch is ahead. Would it be easier to just make a new branch from master and nuke this one?

**Comment by MikeDMorgan** [comment]
Sorry, I meant you have to _locally_ revert _then_ pull from the master branch, then commit your changes. Probs easier to start from scratch as you suggest - but make sure you're local master branch is up-to-date with the remote master branch first.

Sorry this is a hassle - it's quite important to make sure that you always pull from the master branch before making a new branch - and be aware that the master branch may still change so there could be conflicts (hopefully not in this case as we are working on different parts of the repo).

**Comment by MikeDMorgan** [comment]
I'll kill this PR to prevent any issues with it trying to merge anything.

**Pull request closed without merging**
